### ISSUE TITLE
Can't Make Install

### ISSUE THREAD

**Issue by 7h3kk1d** [celery/librabbitmq#101]
Ever since the merging of #99 I can't `make install`:
```
CCLD     examples/amqps_unbind
make[2]: Leaving directory `/home/thekkid/Projects/librabbitmq/rabbitmq-c'
make[1]: Leaving directory `/home/thekkid/Projects/librabbitmq/rabbitmq-c'
mv "rabbitmq-c/rabbitmq-c-0.8.0" "clib"
mv: cannot stat ‘rabbitmq-c/rabbitmq-c-0.8.0’: No such file or directory
make: *** [clib] Error 1
```

Using Ubuntu 14.04. Assuming this is related to the submodule changes.

**Comment by cclauss** [comment]
@matusvalo Do you know how to solve this issue?

**Comment by matusvalo** [comment]
Hi All,

I had a look on the issue and I have found out that I have forgotten to update Makefile :-/. I have created PR #102 fixing this issue. Please take a look and please verify if the PR fixes your problem.

Moreover, I am working also on several other fixes - mainly fixes of unittests. PR is coming soon...
