### ISSUE TITLE
How do I build the development version?

### ISSUE THREAD

**Issue by vgoklani** [celery/librabbitmq#120]
I tried the instructions in the readme:

``
74bee45de169 root@~ $ git clone git://github.com/celery/librabbitmq.git
Cloning into 'librabbitmq'...
remote: Counting objects: 1577, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1577 (delta 1), reused 4 (delta 1), pack-reused 1569
Receiving objects: 100% (1577/1577), 1.53 MiB | 0 bytes/s, done.
Resolving deltas: 100% (818/818), done.
Checking connectivity... done.
74bee45de169 root@~ $ cd librabbitmq/
74bee45de169 root@~/librabbitmq [master] $ ls
AUTHORS               Modules                     funtests      setup.py
Changelog             README.rst                  librabbitmq   tests
LICENSE-GPL-2.0       TODO                        manylinux1    wheelhouse
LICENSE-MPL-RabbitMQ  benchmark.py                rabbitmq-c
MANIFEST.in           build-manylinux1-wheels.sh  requirements
Makefile              contrib                     setup.cfg
74bee45de169 root@~/librabbitmq [master] $ make install
rm -rf build
git submodule init
Submodule 'rabbitmq-c' (https://github.com/alanxz/rabbitmq-c.git) registered for path 'rabbitmq-c'
git submodule update
Cloning into 'rabbitmq-c'...
remote: Counting objects: 6175, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 6175 (delta 6), reused 4 (delta 3), pack-reused 6160
Receiving objects: 100% (6175/6175), 2.63 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4286/4286), done.
Checking connectivity... done.
Submodule path 'rabbitmq-c': checked out 'caad0ef1533783729c7644a226c989c79b4c497b'
(cd rabbitmq-c; test -f configure || autoreconf -i)
/bin/sh: 1: autoreconf: not found
Makefile:18: recipe for target 'rabbitmq-c' failed
make: *** [rabbitmq-c] Error 127
74bee45de169 root@~/librabbitmq [master] $
```

Shouldn't it automatically build the C version?

**Comment by thedrow** [comment]
You need automake/autoconf installed.
