### ISSUE TITLE
Error building librabbitmq 2.0.0 on macOS Mojave 10.14

### ISSUE THREAD

**Issue by zhangjiajie023** [celery/librabbitmq#126]
macOS Mojave 10.14
xcode 10.0
python 3.5.4
the error in config.log is:

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by rabbitmq-c configure 0.8.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ configure --disable-tools --disable-docs --disable-dependency-tracking

## --------- ##

hostname = bogon
uname -m = x86_64
uname -r = 18.0.0
uname -s = Darwin
uname -v = Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64
Kernel configured for up to 4 processors.
2 processors are physically available.
4 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3
Primary memory available: 16.00 gigabytes
Default processor set: 333 tasks, 1546 threads, 4 processors
Load average: 1.58, Mach factor: 2.41
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Users/zhangjiajie/PycharmProjects/walle/venv/bin
PATH: /usr/local/opt/openssl/bin
PATH: /usr/local/opt/mysql@5.7/bin
PATH: /opt/local/sbin
PATH: /opt/local/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /Users/dorayo/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/local/bin
PATH: /opt/local/bin
PATH: /usr/local/mysql/bin
PATH: /Applications/ejabberd-14.07/bin

## ----------- ##

configure:2301: checking for a BSD-compatible install
configure:2369: result: /usr/bin/install -c
configure:2380: checking whether build environment is sane
configure:2435: result: yes
configure:2586: checking for a thread-safe mkdir -p
configure:2625: result: ./install-sh -c -d
configure:2632: checking for gawk
configure:2662: result: no
configure:2632: checking for mawk
configure:2662: result: no
configure:2632: checking for nawk
configure:2662: result: no
configure:2632: checking for awk
configure:2648: found /usr/bin/awk
configure:2659: result: awk
configure:2670: checking whether make sets $(MAKE)
configure:2692: result: yes
configure:2721: checking whether make supports nested variables
configure:2738: result: yes
configure:2875: checking whether make supports nested variables
configure:2892: result: yes
configure:2908: checking whether make supports the include directive
configure:2923: make -f confmf.GNU && cat confinc.out
this is the am__doit target
configure:2926: $? = 0
configure:2945: result: yes (GNU style)
configure:3015: checking for gcc
configure:3031: found /usr/bin/gcc
configure:3042: result: gcc
configure:3271: checking for C compiler version
configure:3280: gcc --version >&5
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
configure:3291: $? = 0
configure:3280: gcc -v >&5
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
configure:3291: $? = 0
configure:3280: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3291: $? = 1
configure:3280: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:3291: $? = 1
**configure:3311: checking whether the C compiler works
configure:3333: gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64  -g -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -arch i386 -arch x86_64  -g -L/usr/local/opt/openssl/lib conftest.c  >&5
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3337: $? = 1
configure:3375: result: no**
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "rabbitmq-c"
| #define PACKAGE_TARNAME "rabbitmq-c"
| #define PACKAGE_VERSION "0.8.0"
| #define PACKAGE_STRING "rabbitmq-c 0.8.0"
| #define PACKAGE_BUGREPORT "https://github.com/alanxz/rabbitmq-c/issues"
| #define PACKAGE_URL "http://www.rabbitmq.com/"
| #define PACKAGE "rabbitmq-c"
| #define VERSION "0.8.0"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
**configure:3380: error: in `/Users/xxx/PycharmProjects/librabbitmq/rabbitmq-c':
configure:3382: error: C compiler cannot create executables**
See `config.log' for more details

## ---------------- ##

......

## ----------------- ##
......

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "rabbitmq-c"
#define PACKAGE_TARNAME "rabbitmq-c"
#define PACKAGE_VERSION "0.8.0"
#define PACKAGE_STRING "rabbitmq-c 0.8.0"
#define PACKAGE_BUGREPORT "https://github.com/alanxz/rabbitmq-c/issues"
#define PACKAGE_URL "http://www.rabbitmq.com/"
#define PACKAGE "rabbitmq-c"
#define VERSION "0.8.0"

configure: exit 77

**Comment by zhangjiajie023** [comment]
is this a existed bug or cased by my env?

**Comment by zhangjiajie023** [comment]
update to 10.14.1 and succeed.

**Comment by agladboy** [comment]
@zhangjiajie023 I had the same problem as you even on Mac OS 10.14.1, would you please share the details about it. Thanks in advance!

**Comment by agladboy** [comment]
The output of mine as followings,
------------------------------------------------------------------
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by rabbitmq-c configure 0.8.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ configure --disable-tools --disable-docs --disable-dependency-tracking

## --------- ##
## Platform. ##
## --------- ##

hostname = Jason.local
uname -m = x86_64
uname -r = 18.2.0
uname -s = Darwin
uname -v = Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64
Kernel configured for up to 8 processors.
4 processors are physically available.
8 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 16.00 gigabytes
Default processor set: 465 tasks, 3195 threads, 8 processors
Load average: 2.58, Mach factor: 5.40
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Users/jason/.virtualenvs/bws-python34/bin
PATH: /Applications/
PATH: /Applications/Postgres.app/Contents/Versions/latest/bin
PATH: /opt/local/bin
PATH: /opt/local/sbin
PATH: /usr/local/git/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2318: checking for a BSD-compatible install
configure:2386: result: /usr/bin/install -c
configure:2397: checking whether build environment is sane
configure:2452: result: yes
configure:2603: checking for a thread-safe mkdir -p
configure:2642: result: /usr/local/bin/gmkdir -p
configure:2649: checking for gawk
configure:2665: found /usr/local/bin/gawk
configure:2676: result: gawk
configure:2687: checking whether make sets $(MAKE)
configure:2709: result: yes
configure:2738: checking whether make supports nested variables
configure:2755: result: yes
configure:2892: checking whether make supports nested variables
configure:2909: result: yes
configure:2925: checking whether make supports the include directive
configure:2940: make -f confmf.GNU && cat confinc.out
this is the am__doit target
configure:2943: $? = 0
configure:2962: result: yes (GNU style)
configure:3032: checking for gcc
configure:3048: found /usr/bin/gcc
configure:3059: result: gcc
configure:3288: checking for C compiler version
configure:3297: gcc --version >&5
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
configure:3308: $? = 0
configure:3297: gcc -v >&5
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
configure:3308: $? = 0
configure:3297: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:3308: $? = 1
configure:3297: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:3308: $? = 1
configure:3328: checking whether the C compiler works
configure:3350: gcc -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64  -g  -arch i386 -arch x86_64  -g conftest.c  >&5
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
ld: dynamic main executables must link with libSystem.dylib for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3354: $? = 1
configure:3392: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "rabbitmq-c"
| #define PACKAGE_TARNAME "rabbitmq-c"
| #define PACKAGE_VERSION "0.8.0"
| #define PACKAGE_STRING "rabbitmq-c 0.8.0"
| #define PACKAGE_BUGREPORT "https://github.com/alanxz/rabbitmq-c/issues"
| #define PACKAGE_URL "http://www.rabbitmq.com/"
| #define PACKAGE "rabbitmq-c"
| #define VERSION "0.8.0"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3397: error: in `/Users/jason/bws/librabbitmq/rabbitmq-c':
configure:3399: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64  -g'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-arch i386 -arch x86_64  -g'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_POPT_CFLAGS_set=
ac_cv_env_POPT_CFLAGS_value=
ac_cv_env_POPT_LIBS_set=
ac_cv_env_POPT_LIBS_value=
ac_cv_env_SSL_CFLAGS_set=
ac_cv_env_SSL_CFLAGS_value=
ac_cv_env_SSL_LIBS_set=
ac_cv_env_SSL_LIBS_value=
ac_cv_env_XMLTO_set=
ac_cv_env_XMLTO_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/local/bin/gmkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /Users/jason/bws/librabbitmq/rabbitmq-c/missing aclocal-1.16'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE='#'
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
AR=''
AS=''
AUTOCONF='${SHELL} /Users/jason/bws/librabbitmq/rabbitmq-c/missing autoconf'
AUTOHEADER='${SHELL} /Users/jason/bws/librabbitmq/rabbitmq-c/missing autoheader'
AUTOMAKE='${SHELL} /Users/jasonzhang/bws/librabbitmq/rabbitmq-c/missing automake-1.16'
AWK='gawk'
CC='gcc'
CCDEPMODE=''
CFLAGS='-fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64  -g'
CPP=''
CPPFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
DLLTOOL=''
DOCS_FALSE=''
DOCS_TRUE=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
EXAMPLES_FALSE=''
EXAMPLES_TRUE=''
EXEEXT=''
FGREP=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS='-arch i386 -arch x86_64  -g'
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_AGE=''
LT_CURRENT=''
LT_REVISION=''
LT_SYS_LIBRARY_PATH=''
MAKEINFO='${SHELL} /Users/jason/bws/librabbitmq/rabbitmq-c/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/usr/local/bin/gmkdir -p'
NM=''
NMEDIT=''
NO_UNDEFINED=''
OBJDUMP=''
OBJEXT=''
OS_APPLE_FALSE=''
OS_APPLE_TRUE=''
OS_UNIX_FALSE=''
OS_UNIX_TRUE=''
OS_WIN32_FALSE=''
OS_WIN32_TRUE=''
OTOOL64=''
OTOOL=''
PACKAGE='rabbitmq-c'
PACKAGE_BUGREPORT='https://github.com/alanxz/rabbitmq-c/issues'
PACKAGE_NAME='rabbitmq-c'
PACKAGE_STRING='rabbitmq-c 0.8.0'
PACKAGE_TARNAME='rabbitmq-c'
PACKAGE_URL='http://www.rabbitmq.com/'
PACKAGE_VERSION='0.8.0'
PATH_SEPARATOR=':'
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
POPT_CFLAGS=''
POPT_LIBS=''
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
SSL_CFLAGS=''
SSL_FALSE=''
SSL_LIBS=''
SSL_OPENSSL_FALSE=''
SSL_OPENSSL_TRUE=''
SSL_TRUE=''
STRIP=''
TOOLS_FALSE=''
TOOLS_TRUE=''
VERSION='0.8.0'
XMLTO=''
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /Users/jason/bws/librabbitmq/rabbitmq-c/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
libs_private=''
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
requires_private=''
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "rabbitmq-c"
#define PACKAGE_TARNAME "rabbitmq-c"
#define PACKAGE_VERSION "0.8.0"
#define PACKAGE_STRING "rabbitmq-c 0.8.0"
#define PACKAGE_BUGREPORT "https://github.com/alanxz/rabbitmq-c/issues"
#define PACKAGE_URL "http://www.rabbitmq.com/"
#define PACKAGE "rabbitmq-c"
#define VERSION "0.8.0"

configure: exit 77
