### ISSUE TITLE
librabbitmq 2.0.0 doesn't work with BSON?

### ISSUE THREAD

**Issue by chanpl** [celery/librabbitmq#128]
My message is encoded in BSON format, but it seems librabbitmq doesn't work with that.

**Error message:**
`  File "python3.6/site-packages/librabbitmq/__init__.py", line 122, in basic_publish
    mandatory or False, immediate or False,
TypeError: argument 2 must be read-only bytes-like object, not memoryview
`

Appreciate if someone can acknowledge this issue.

**Comment by auvipy** [comment]
no this isn't supported

**Comment by chanpl** [comment]
After my investigation, the problem is happened when I republish a message which message body is in memoryview type. This is resolved by converting the message body from memoryview to bytes.
