### ISSUE TITLE
Can't install on python:3.6.6-alpine container 

### ISSUE THREAD

**Issue by arossert** [celery/librabbitmq#129]
When I install librabbitmq on `python:3.6.6-alpine` container with pip it seems that the install successes but the module is not installed:

`/ # pip install librabbitmq
Collecting librabbitmq
  Downloading https://files.pythonhosted.org/packages/f4/4e/8f8bf33d44f3441d6f6c29b299cc847570b2c864bd8d2f9871aa6c03b73e/librabbitmq-2.0.0.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 469kB/s
Collecting amqp>=1.4.6 (from librabbitmq)
  Downloading https://files.pythonhosted.org/packages/7f/cf/12d4611fc67babd4ae250c9e8249c5650ae1933395488e9e7e3562b4ff24/amqp-2.3.2-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 5.0MB/s
Collecting six>=1.0.0 (from librabbitmq)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting vine>=1.1.3 (from amqp>=1.4.6->librabbitmq)
  Downloading https://files.pythonhosted.org/packages/62/dd/e30f828a39914626d67876b987d6fc47616b64de680cd0f746fc9c8aab47/vine-1.2.0-py2.py3-none-any.whl
Building wheels for collected packages: librabbitmq
  Running setup.py bdist_wheel for librabbitmq ... done
  Stored in directory: /root/.cache/pip/wheels/46/99/72/9044c0db1616e4ad40f5c518041883b38896117cfe18016a1f
Successfully built librabbitmq
Installing collected packages: vine, amqp, six, librabbitmq
Successfully installed amqp-2.3.2 librabbitmq-2.0.0 six-1.12.0 vine-1.2.0`

And when I try to use it I get
`Python 3.6.6 (default, Sep 12 2018, 02:15:29)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librabbitmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'librabbitmq'`

After looking at the `site-packages` it seems that only this directory was installed `librabbitmq-2.0.0.dist-info`

Doing the same on `python:3.6.6` image which brings debian9 it is working.

**Comment by thedrow** [comment]
Please report this upstream. This is not a problem with the python bindings.
See #130
