### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by thijstriemstra** [celery/librabbitmq#13]
It would be nice to support Python 3 at some point. Getting this error at the moment when running `python3.3 setup.py build`:

```
File "setup.py", line 185
    except Exception, exc:
                ^
SyntaxError: invalid syntax
```

**Comment by grahamc** [comment]
Oh what the heck, +1

**Comment by dwieeb** [comment]
+1

**Comment by zloy531** [comment]
+1

**Comment by gavinmh** [comment]
+1 for Python3

**Comment by r-darwish** [comment]
+1

**Comment by mark-adams** [comment]
+1

**Comment by mstajdohar** [comment]
+1

**Comment by myroid** [comment]
+1

**Comment by dgelvin** [comment]
Made a first attempt at this [here](https://github.com/celery/librabbitmq/pull/66).

**Comment by iyn** [comment]
+1

**Comment by aidanlister** [comment]
+1

**Comment by underyx** [comment]
+1

**Comment by btoueg** [comment]
+1

**Comment by mastak** [comment]
+1

**Comment by ajutras** [comment]
+1

**Comment by anthraxx** [comment]
+1

**Comment by arthurk** [comment]
+1

**Comment by malinoff** [comment]
I think it is enough of "+1"s. I'm going to lock this issue not because we won't add python 3 support, but to avoid messing up our mailboxes.

If anybody of "+1"ers have some time, please spend it on creating pull requests for python 3 support. Thank you.

**Comment by auvipy** [comment]
@ask @malinoff I am gonna tackle this issue to support python

**Comment by berkerpeksag** [comment]
I think the next step would be to improve the test suite. We especially need to test the Connection object and its methods return types.
