### ISSUE TITLE
Support version Python >= 3.7

### ISSUE THREAD

**Issue by mushishi06** [celery/librabbitmq#137]
Fallowing multiple test / try and update to latest version (even dev Branch, `rabbitmq-c`), 
it appears to me to **NOT** be compatible with Python version superior to 3.6

- tested with Python `**3.7.3**`, `**3.8.0**` => Failed

- tested with Python `**3.6.9**` => success

Did you schedule the support for the new version of Python?

Thank you in advance.

**Comment by thedrow** [comment]
This library is deprecated.
PRs are welcome but we're not going to invest more time in it.

**Comment by mushishi06** [comment]
Thanks for the update.
Waiting for the new version of celery :+1:

**Comment by c-nichols** [comment]
I'm having trouble finding info about this deprecation, recommended replacement, etc.  @thedrow can you provide more details or point me toward some docs?

**Comment by thedrow** [comment]
Unfortunately we didn't officially deprecate it but we don't have the time to support it.
py-amqp is our AMQP client that we do have time to maintain.

Again, PRs are welcome. We simply don't have the bandwidth to maintain this library.

**Comment by c-nichols** [comment]
OK thanks

@mushishi06 could you describe what sort of issues you ran into?  The tests pass on 3.7 so I'm not sure where to begin
