### ISSUE TITLE
Installing as install_requires via setup.py fails.

### ISSUE THREAD

**Issue by ygzgxyz** [celery/librabbitmq#32]
Environment: OS X 10.8.5, Python 2.7.2

installing directly via pip command works well as expected, but installing via `setup.py develop` as specifying `librabbitmq` as `install_requires` causes an error. the last part of error is:

```
clang: warning: argument unused during compilation: '-mno-fused-madd'
clib/librabbitmq/amqp_mem.c:46:10: error: use of undeclared identifier 'VERSION'
  return VERSION; /* defined in config.h */
         ^
1 error generated.
error: Setup script exited with error: command 'clang' failed with exit status 1
```

i've tried specifying _librabbitmq_ in _setup_requires_, but it generated same result. how can i fix this situation? i want to get rid of calling `pip install -r requirements.txt` from my application.

**Comment by willtrking** [comment]
I'm currently having a similar issue (although the error is different)

Environment: Ubuntu 14.04 LTS, Python 2.7.3

Error output
```
clib/librabbitmq/amqp_socket.c:1195:28: error: 'AMQ_PLATFORM' undeclared (first use in this function)
clib/librabbitmq/amqp_socket.c:1195:28: note: each undeclared identifier is reported only once for each function it appears in
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

setuptools is running 
```
librabbitmq-1.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-u4v43t/librabbitmq-1.6.1/egg-dist-tmp-Fjo5LN
```

Would seem like if the "bdist_egg" forced a build in the setup.py file this would go away?

**Comment by rosarior** [comment]
Same issue on clean install of Fedora 22 Desktop 64 bit, Python 2.7.10.

**Comment by rosarior** [comment]
Manual build command returns:
