### ISSUE TITLE
librabbitmq build fails on OS X Lion

### ISSUE THREAD

**Issue by fredrik** [celery/librabbitmq#6]
Installation of librabbitmq fails with the message below. This happens when installing using pip (`pip install librabbitmq==0.9.9`) and when using the development version (ref f29317eb4d).

```
/usr/bin/clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fno-strict-aliasing -fno-common -dynamic -Os -w -pipe -march=native -Qunused-arguments -mmacosx-version-min=10.7 -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -W -Wall -ansi -Iclib/librabbitmq -Iclib -Iclib/librabbitmq/unix -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c clib/librabbitmq/amqp_api.c -o build/temp.macosx-10.7-x86_64-2.7/clib/librabbitmq/amqp_api.o
clib/librabbitmq/amqp_api.c:33:10: fatal error: 'config.h' file not found
#include "config.h"
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
make: *** [build] Error 1
```

([Full log](https://gist.github.com/3169324#file_gistfile1.txt))

I propose adding `(cd clib; test -f clib/config.h || ./configure)` to [the Makefile's dist target](https://raw.github.com/gist/3169324/b4040d4c2452f9044002d12a420ee870c49d1a03/Makefile.diff). This will generate the needed config.h file and the build will succeed.

**Comment by auvipy** [comment]
should have been fixed by now. or still issues with that? 1.6.1 works well?

**Comment by creslinux** [comment]
I'm running into this, spent the morning trying various means to install librabbitmq to no luck

Is there an how-to install on OXS? 
Im on python 3.6, virtual-env 

I've installed: 

- brew install autoconf
- brew install automake
- brew install pkg-config

Ive tried: 

- git clone https://github.com/celery/librabbitmq.git
- cd librabbitmq
- git submodule init
- git submodule update

pip, pip3, easy_install.. same deal every time 
`error: command 'clang' failed with exit status 1`

**Comment by auvipy** [comment]
use py-amqp this library is not recommended anymore.
