### ISSUE TITLE
Is it a dual license?

### ISSUE THREAD

**Issue by vitaly-krugl** [celery/librabbitmq#67]
Hi @ask, I would like to use this package, but the license situation is a bit confusing:

The repo contains two licenses:
1. LICENSE-GPL-2.0
2. LICENSE-MPL-RabbitMQ

However, both README.rst and PyPi https://pypi.python.org/pypi/librabbitmq#license both make it seem like it's a single MPL license:

> This software is licensed under the Mozilla Public License. See the LICENSE-MPL-RabbitMQ file in the top distribution directory for the full license text.

Could you possibly clarify the licensing terms as soon as possible? The MPL license is not compatible with my app, while GPL-2.0 would be compatible.

Many thanks,
Vitaly

**Comment by ask** [comment]
Hey Vitaly

The license was the same as for rabbitmq-c, which ummm, seems to be MIT licensed now.

Since the distribution includes rabbitmq-c I chose the same dual licensing to be compatible, but if you can help me verify that they have changed to MIT we can change also.

**Comment by rhyolight** [comment]
@ask I've found the commits in rabbitmq-c that evidences the license change from GPLv2.0 to MIT on April 12, 2012:

- [Drop COPYING and old LICENSES](https://github.com/alanxz/rabbitmq-c/commit/a10cb49fe217bbbb825931403edeb74e4694624c)
- [Add MIT license and update debian scripts to use it](https://github.com/alanxz/rabbitmq-c/commit/17ecc432196dad65009749e4456ed29febd61f63#diff-7f0bdbc0a0545831259b66259ac6b604)

/cc @vitaly-krugl

**Comment by vitaly-krugl** [comment]
Thanks @rhyolight!

**Comment by todofixthis** [comment]
We are performing an audit of all the OSS that we are using at our company.  What should I put in the Licence column next to librabbitmq?

**Comment by auvipy** [comment]
issue is resolved i guess

**Comment by hrieke** [comment]
This is confusing and needs to be cleaned up.
Can you please update the license properly (and include the updated license information in the headers of the files too?  Even better would be to reference this issue in the readme notes!).  Thank you.

**Comment by rhyolight** [comment]
Yeah I'd say this issue is still open seeing how there are still two licenses. Which one do we use? @ask said there reason it was gpl was because rabbitmq-c was, but that was changed to MIT. If there are two licenses there should be a statement somewhere about how they should be applied.
