### ISSUE TITLE
pip install fails on Fedora 

### ISSUE THREAD

**Issue by amitsaha** [celery/librabbitmq#71]
Hello,

Attempting to install on F22 results in:

```
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fno-strict-aliasing -O2 -g -pipe -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Iclib/librabbitmq -Iclib -I/usr/include/python2.7 -c clib/librabbitmq/amqp_socket.c -o build/temp.linux-x86_64-2.7/clib/librabbitmq/amqp_socket.o

    clib/librabbitmq/amqp_socket.c: In function 'amqp_login_inner':

    clib/librabbitmq/amqp_socket.c:1195:28: error: 'AMQ_PLATFORM' undeclared (first use in this function)

             amqp_cstring_bytes(AMQ_PLATFORM);

                                ^

    clib/librabbitmq/amqp_socket.c:1195:28: note: each undeclared identifier is reported only once for each function it appears in

    error: command 'gcc' failed with exit status 1


```

Any idea how I can fix this please?

**Comment by agriffis** [comment]
See #68 and the comment in #69 ... the latter might be a pointer in the right direction on Fedora.

**Comment by amitsaha** [comment]
This is still failing to install on Fedora 23 with the same error as above.

**Comment by amitsaha** [comment]
Okay, here is something more encouraging i guess:

- I downloaded the source from PyPi for 1.6.1
- extracted it
- cd clib; ./configure; make install
- cd ../ 
- python setup.py install


And it succeeds!

**Comment by stephen144** [comment]
Also successful following previous comment on Fedora 23.

**Comment by david-caro** [comment]
Yep, the current code that's on pypi it's from 2014 and does not include the patches @agriffis mentioned. When should we expect the next release on pypi? ;)

**Comment by amitsaha** [comment]
I recently built some `manylinux1` wheels (https://github.com/celery/librabbitmq/pull/87). These manylinux1 wheels are installable on Fedora without any issues. Please check my PR there and you can start using librabbitmq on Fedora without any issues. We just need to now start pushing manylinux1 wheels to PyPi.

**Comment by usrlocalben** [comment]
bump.

fc25.

I installed it similar to the comment above, but it is not necessary to `make install` .

```
wget 'https://pypi.python.org/packages/82/6c/1b3f7ca755787e934513039131091134038239f167e1bc50565cb46112a0/librabbitmq-1.6.1.tar.gz#md5=716f05388d4747ea605c1a31f8541e3b'
tar xzf librabbitmq-1.6.1.tar.gz
cd librabbitmq-1.6.1/clib
./configure
make
cd ..
python setup.py install
```

Running `setup.py install` without having built the binaries with `make` is not enough -- it will terminate with the same error as OP.

**Comment by cepradeep** [comment]
I had the same issue when installing `librabbitmq` using `pip`. If having `1.6.1` isn't critical for you, and installing via `pip` is something you simply must retain, then the easiet thing to do is:

```
pip install librabbitmq==1.5.1
```

I don't yet know why this works and the newer version doesn't. I'll post here if I find out. Also, I am not an expert; so please take this with a pinch of salt.

**Comment by auvipy** [comment]
https://github.com/celery/librabbitmq/releases/tag/v2.0.0
