### ISSUE TITLE
Old version of rabbitmq-c

### ISSUE THREAD

**Issue by czpython** [celery/librabbitmq#77]
Hello,
I've noticed the git submodule references a fork which has not been updated with latest code from rabbitmq-c, is this intentional? meaning is this library not compatible with the last code in rabbitmq-c?

**Comment by mverrilli** [comment]
@ask Is there any interest in updating this? I could take a stab at it.

**Comment by dhui** [comment]
+1 for updating the rabbitmq-c library
It looks like newer versions of rabbitmq-c support hearbeats: https://github.com/alanxz/rabbitmq-c/issues/259

**Comment by fake-name** [comment]
I've been looking around in the source, and it's basically impossible to follow. Dynamically generated C output from python via print, huge multi-line string literals everywhere.

I almost think starting over with something like SWIG is a better option for supporting py3k/recent versions of AMQP.

**Comment by mverrilli** [comment]
@fake-name That code generation is based on protocol specs and really doesn't require you to touch it. I think mostly this is about getting python wrappers around the rabbitmq-c api then updating kombu appropriately. 

I really don't know what the effort is, though, to get the python wrapper working with python 3.x.

**Comment by fake-name** [comment]
@mverrilli - I was wading through python code that emitted python-wrapping C code by printing to stdout the other night, but I can't find it in the repository. 

In any event, the build process is extremely opaque at minimum.

I'll see if I can be specific about what I was seeing once I'm home later.

**Comment by fake-name** [comment]
Ok, you're correct, and I have no idea what I was looking at.

I do have to still touch that code, because I'm trying (and failing) at a py3k port, and it uses the `print` construct everywhere, but that's at least somewhat pedestrian.

**Comment by auvipy** [comment]
https://github.com/celery/librabbitmq/releases/tag/v2.0.0 check this
