### ISSUE TITLE
Wrong sending timestamp

### ISSUE THREAD

**Issue by Zartul** [celery/librabbitmq#79]
I try to send timestamp value with message but it is rounded to 255. If i sent 256 I'll receive 0, 257 - 1, 258 - 2 etc.
in librabbitmq/Modules/_librabbitmq/connection.c
I see setting timestamp as long:

``` c++
    if (props->_flags & AMQP_BASIC_TIMESTAMP_FLAG) {
        value = PyInt_FromLong(props->timestamp);
        PyDICT_SETSTR_DECREF(p, "timestamp", value);
    }
```

and getting it with casting to uint8_t type:

``` c++
    if ((value = PyDict_GetItemString(p, "timestamp")) != NULL) {
        props->timestamp = (uint8_t)PyInt_AS_LONG(value);
        props->_flags |= AMQP_BASIC_TIMESTAMP_FLAG;
    }
```

I suppose this casting to uint8_t is a reason of my issue. Is it right behavior for timestamp property in message?

**Comment by auvipy** [comment]
try https://github.com/celery/librabbitmq/releases/tag/v2.0.0 or py-amqp

**Comment by rodolfo-picoreti** [comment]
Hi, I am having the same issue using librabbitmq v2.0.0. Published timestamps are being wrongly casted to uint8_t instead of uint64_t and therefore being truncated. It seems its been this way for six years now.
