### ISSUE TITLE
Accept a Connection socket_timeout

### ISSUE THREAD

**Issue by dtran320** [celery/librabbitmq#8]
pylibrabbitmq does not appear to accept a socket_timeout like amqplib and other transports do, resulting in the following unexpected `ConnectionError`.

With librabbitmq:
-----------------
librabbitmq/__init__.pyc in __init__(self, host, userid, password, virtual_host, port, channel_max, frame_max, heartbeat, lazy, **kwargs)
    166         self._avail_channel_ids = array('H', xrange(self.channel_max, 0, -1))
    167         if not lazy:
--> 168             self.connect()
    169 
    170     def reconnect(self):

ConnectionError: Error opening socket: Unknown error: 536870972

With amqplib:
-------------

amqplib/client_0_8/transport.pyc in __init__(self, host, connect_timeout)
     83         if not self.sock:
     84             # Didn't connect, return the most recent error message

---> 85             raise socket.error, msg
     86 
     87         self.sock.settimeout(None)

timeout: timed out

Running kombu 2.4.6 with librabbitmq: calls to `.delay()` and `.apply_async()`
that time out no longer timeout in the amount of time set with `BROKER_CONNECTION_TIMEOUT`
as they did with amqplib.

**Comment by auvipy** [comment]
@dtran320 new maintainer here, does the latest versions resolve this issue?

**Comment by dtran320** [comment]
@auvipy Congrats on the new gig! I haven't really been actively developing anything with this library recently, but I'm pretty sure the issue was resolved at some point in the project i was working on previously, so I'll go ahead and close this.
