### ISSUE TITLE
How to gracefully shutdown a blocking connection?

### ISSUE THREAD

**Issue by roshansingh** [celery/librabbitmq#80]
I am using a blocking connection which does file io, I want to be able to do some cleanup before killing the process. How to do this?

**Comment by mverrilli** [comment]
I don't know for sure, and I don't know specifically which calls you are referring to but I typically will do small event loops using blocking with a timeout so I can look for conditions like exit and cleanup. You could also possibly use a signal to catch and cleanup. Just some ideas.
