### ISSUE TITLE
Benchmark against py-amqp

### ISSUE THREAD

**Issue by caulagi** [celery/librabbitmq#84]
The project description in this repo and celery docs recommend using librabbitmq.  I was wondering if there are benchmarks against py-amqp (https://github.com/celery/py-amqp).  I see a benchmark.py in the repo but that seems to compare amqplib and not py-amqp.  

Will there be a difference in a project that is already using py-amqp to use librabbitmq?

**Comment by caulagi** [comment]
Ping @ask.  Do you have any suggestions on where I should look?  Thanks!

**Comment by mverrilli** [comment]
Hi, where is the benchmark.py at? I use librabbitmq (on Solaris) and could test it there for you.

**Comment by caulagi** [comment]
@mverrilli - I am referring to https://github.com/celery/librabbitmq/blob/master/benchmark.py.  As you can see, it compares librabbitmq and amqplib.  I am wonder what the performance differences are between py-amqp and librabbitmq.

**Comment by mverrilli** [comment]
Here you go.  The APIs are compatible so it's not hard to add pyamqp to the benchmark. 

https://github.com/mverrilli/librabbitmq/blob/6cab55310f80fd57a893c5af94f88111fff97666/benchmark.py

I don't have a clean system to run the benchmark on though. When I can get one set up I'll be happy to run it.

**Comment by caulagi** [comment]
Ok, thanks.  I read the code a bit too quickly and was looking for `librabbit.benchmark` as a python module.  So I get these results - 

```
basic.publish: (256 byte messages)
    amqplib:   8.11 usec/pass
    librabbit: 24.87 usec/pass
    pyamqp:    35.40 usec/pass
basic.consume (5000 msg/pass)
    amqplib:   31.86 usec/pass
    librabbit: 7.47 usec/pass
    pyamqp:    8.98 usec/pass
```

I used rabbitmq available as a docker container -

```
docker run -p 5672:5672 -p 5671:5671 -p 25672:25672 rabbitmq                                                                                                              ⏎

              RabbitMQ 3.6.3. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...

=INFO REPORT==== 21-Jul-2016::12:44:13 ===
Starting RabbitMQ 3.6.3 on Erlang 18.3
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 21-Jul-2016::12:44:13 ===
node           : rabbit@9c97037dc1ba
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : z9fD3yHpmNSECwFN6gMR7Q==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@9c97037dc1ba
```

So is my reading correct that **pyamqp is better**?

**Comment by david-caro** [comment]
I'm not sure about the correctness of the benchmark (that's a science by itself) but for the results you posted, I'd say that for publishing small messages, amqplib is way *faster* than the others, with librabbit in a far second position. For consumers, librabbit is the fastest, but with pyamqp very close, and amqplib in a far third position.

So for those numbers it seems to me that pyamqp is always slower than librabbit.

**Comment by thedrow** [comment]
Since we're replacing this library it does not really matter.
