### ISSUE TITLE
ImproperlyConfigured: Unknown result backend: 'librabbitmq'

### ISSUE THREAD

**Issue by kharazi** [celery/librabbitmq#85]
According to [document of celery](http://docs.celeryproject.org/en/latest/userguide/optimizing.html#librabbitmq-python-2-only), when i set `librabbitmq` before my broker of celery, i got this error:

`ImproperlyConfigured: Unknown result backend: 'librabbitmq'.  Did you spell that correctly? ('is a Python module, not a backend class.')
`
librabbitmq, was installed in virtualenv correctly:
```
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import librabbitmq
>>> 

```

How can I ensure it use librabbitmq?

**Comment by mverrilli** [comment]
That doc refers to the broker, not the backend (notice your error). It's probably not advisable to use amqp as a backend and I doubt it has the librabbitmq-specific URL capability.  If that's what you are looking for, then consider using rpc:// instead.  I personally use memcached without any issues, and if you want to persist the backend results then you'd maybe consider redis or other.

Hope this helps.

**Comment by auvipy** [comment]
@kharazi you are putting on the wrong hole. try to follow @mverrilli comment
