### ISSUE TITLE
make install fails with "error: Libtool library used but 'LIBTOOL' is undefined"

### ISSUE THREAD

**Issue by edmorley** [celery/librabbitmq#90]
I'm trying to build from source on Ubuntu 16.04, since the latest pypi release is 2 years old.

The readme [says](https://github.com/celery/librabbitmq#using-the-development-version) to:
- $ `git clone git://github.com/celery/librabbitmq.git`
- $ `cd librabbitmq`
- $ `make install`

However even after installing libtool (plus a number of other deps not explicitly called out in the README), I still get:

```
$ make install
rm -rf build
git submodule init
git submodule update
(cd rabbitmq-c; rm -rf codegen; ln -sf ../rabbitmq-codegen ./codegen)
(cd rabbitmq-c; test -f configure || autoreconf -i)
(cd rabbitmq-c; test -f Makefile  || automake --add-missing)
Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:6:   its definition is in aclocal's search path.
Makefile:22: recipe for target 'rabbitmq-c' failed
make: *** [rabbitmq-c] Error 1
```

**Comment by amitsaha** [comment]
I don't have a solution to your issue. But, can you try building the manylinux1 wheels (see: https://github.com/celery/librabbitmq/pull/87) and then installing those?

**Comment by edmorley** [comment]
I don't have docker installed at the moment, I'll give this a go when I do in the future.

**Comment by dmitry-kostin** [comment]
also have this issue, anybody have the solution to bypass it ?

**Comment by danigosa** [comment]
On Alpine Linux Dockerfile:

```
apk add --update \
    libtool \
    cmake \
    autoconf \
    automake && \
    cd / && \
    git clone https://github.com/celery/librabbitmq.git && \
    cd librabbitmq/ && \
    git checkout tags/2.0.0 && \
    make install && \
    cd .. && rm -rf librabbitmq
```
