### ISSUE TITLE
librabbitmq 1.6.1 doesn't work with Celery4.0.2

### ISSUE THREAD

**Issue by acidjunk** [celery/librabbitmq#93]
When trying to use Celery4.0.2 with librabbitmq; celery refuses to accept messages with:

`[2017-02-17 08:51:59,251: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?`

The problem is also describe here: https://github.com/celery/celery/issues/3675

Will there be an update or are we better of by using amqp?

**Comment by sfdye** [comment]
+1 for this

**Comment by auvipy** [comment]
it's safe to use py-amqp but you could also test https://github.com/celery/librabbitmq/releases/tag/v2.0.0
